services:
  quality-lab-service:
    build: .
    container_name: qls-api
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__QualityLabDb: "${QLS_DB_CONNECTION:?Set QLS_DB_CONNECTION in .env}"
      Kafka__BootstrapServers: "kafka:9092"
    networks: [wonrich-net]

networks:
  wonrich-net:
    external: true
